plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.lenswireproxy'
version = '0.1.0'

android {
  namespace "expo.modules.lenswireproxy"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "androidx.core:core-ktx:1.15.0"
  implementation "org.bouncycastle:bcprov-jdk18on:1.78.1"
  implementation "org.bouncycastle:bcpkix-jdk18on:1.78.1"
}
